name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer Action
        uses: akshayaurora/buildozer-action@v1.2.0
        with:
          command: buildozer android debug
          repository_read_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TikFPS-APK
          path: bin/*.apk
